
package proyecto;

/**
 *
 * @author Usuario
 */
public class Letras2 extends javax.swing.JFrame {

    /**
     * Creates new form Letras2
     */
    public Letras2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jugadornombre = new javax.swing.JTextField();
        fallos = new javax.swing.JTextField();
        aciertos = new javax.swing.JTextField();
        salirdeljuego = new javax.swing.JButton();
        vocalA = new javax.swing.JButton();
        vocalE = new javax.swing.JButton();
        vocalI = new javax.swing.JButton();
        vocalO = new javax.swing.JButton();
        vocalU = new javax.swing.JButton();
        letraintento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 255));
        jLabel1.setText("Jugador:");

        jLabel2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("Fallos:");

        jLabel3.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Aciertos:");

        jugadornombre.setText("jTextField1");
        jugadornombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadornombreActionPerformed(evt);
            }
        });

        fallos.setText("jTextField2");

        aciertos.setText("jTextField3");

        salirdeljuego.setBackground(new java.awt.Color(51, 255, 0));
        salirdeljuego.setFont(new java.awt.Font("Vineta BT", 0, 24)); // NOI18N
        salirdeljuego.setText("SALIR DEL JUEGO");
        salirdeljuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirdeljuegoMouseClicked(evt);
            }
        });
        salirdeljuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirdeljuegoActionPerformed(evt);
            }
        });

        vocalA.setBackground(new java.awt.Color(153, 255, 153));
        vocalA.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        vocalA.setForeground(new java.awt.Color(0, 255, 255));
        vocalA.setText("A");
        vocalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalAActionPerformed(evt);
            }
        });

        vocalE.setBackground(new java.awt.Color(153, 255, 153));
        vocalE.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        vocalE.setForeground(new java.awt.Color(0, 255, 255));
        vocalE.setText("E");
        vocalE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalEActionPerformed(evt);
            }
        });

        vocalI.setBackground(new java.awt.Color(153, 255, 153));
        vocalI.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        vocalI.setForeground(new java.awt.Color(0, 255, 255));
        vocalI.setText("I");
        vocalI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalIActionPerformed(evt);
            }
        });

        vocalO.setBackground(new java.awt.Color(153, 255, 153));
        vocalO.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        vocalO.setForeground(new java.awt.Color(0, 255, 255));
        vocalO.setText("O");
        vocalO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalOActionPerformed(evt);
            }
        });

        vocalU.setBackground(new java.awt.Color(153, 255, 153));
        vocalU.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        vocalU.setForeground(new java.awt.Color(0, 255, 255));
        vocalU.setText("U");
        vocalU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vocalUActionPerformed(evt);
            }
        });

        letraintento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraintentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugadornombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fallos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vocalA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vocalI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vocalE)
                            .addComponent(vocalO)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(vocalU)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(salirdeljuego))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(letraintento, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jugadornombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fallos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aciertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vocalA)
                    .addComponent(vocalE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vocalI)
                            .addComponent(vocalO))
                        .addGap(18, 18, 18)
                        .addComponent(vocalU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(salirdeljuego)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(letraintento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugadornombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadornombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadornombreActionPerformed

    private void salirdeljuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirdeljuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirdeljuegoActionPerformed

    private void salirdeljuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirdeljuegoMouseClicked
        // SALIR DE LA APLICACION:
       
        System.exit(0); // Cierra la aplicación
      
    }//GEN-LAST:event_salirdeljuegoMouseClicked

    private void vocalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalAActionPerformed
        // TODO add your handling code here:
        String letra =vocalA.getText();
        letraintento.setText(letraintento.getText()+letra);
    }//GEN-LAST:event_vocalAActionPerformed

    private void vocalEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalEActionPerformed
        // TODO add your handling code here:
        String letra =vocalE.getText();
        letraintento.setText(letraintento.getText()+letra);
    }//GEN-LAST:event_vocalEActionPerformed

    private void vocalIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalIActionPerformed
        // TODO add your handling code here:
        String letra =vocalI.getText();
        letraintento.setText(letraintento.getText()+letra);
    }//GEN-LAST:event_vocalIActionPerformed

    private void vocalOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalOActionPerformed
        // TODO add your handling code here:
        String letra =vocalO.getText();
        letraintento.setText(letraintento.getText()+letra);
    }//GEN-LAST:event_vocalOActionPerformed

    private void vocalUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vocalUActionPerformed
        // TODO add your handling code here:
        String letra =vocalU.getText();
        letraintento.setText(letraintento.getText()+letra);
    }//GEN-LAST:event_vocalUActionPerformed

    private void letraintentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraintentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letraintentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Letras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Letras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Letras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Letras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Letras2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aciertos;
    private javax.swing.JTextField fallos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jugadornombre;
    private javax.swing.JTextField letraintento;
    private javax.swing.JButton salirdeljuego;
    private javax.swing.JButton vocalA;
    private javax.swing.JButton vocalE;
    private javax.swing.JButton vocalI;
    private javax.swing.JButton vocalO;
    private javax.swing.JButton vocalU;
    // End of variables declaration//GEN-END:variables
}
